spring.application.name=votacao
spring.datasource.url=jdbc:postgresql://localhost:5432/votacao
spring.datasource.username=${DB_USER:votacao}
spring.datasource.password=${DB_PASSWORD:votacao}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true