CREATE TABLE pauta
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo      VARCHAR(255) NOT NULL,
    descricao   VARCHAR(1000),
    criada_em   TIMESTAMP    NOT NULL
);

CREATE TABLE sessao_votacao
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id   BIGINT    NOT NULL,
    abertura   TIMESTAMP NOT NULL,
    fechamento TIMESTAMP NOT NULL,
    CONSTRAINT fk_sessao_pauta FOREIGN KEY (pauta_id) REFERENCES pauta (id),
    CONSTRAINT uk_sessao_pauta UNIQUE (pauta_id)
);

CREATE TABLE voto
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id    BIGINT      NOT NULL,
    associado_id VARCHAR(11) NOT NULL,
    voto         VARCHAR(3)  NOT NULL,
    criado_em    TIMESTAMP   NOT NULL,
    CONSTRAINT fk_voto_sessao FOREIGN KEY (sessao_id) REFERENCES sessao_votacao (id),
    CONSTRAINT uk_voto_sessao_associado UNIQUE (sessao_id, associado_id)
);

CREATE INDEX idx_voto_sessao_id ON voto (sessao_id);